name: API workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    runs-on: macos-latest
    name: Test python API
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov --cov-report xml .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        flags: api
