name: API workflow

on: [push, pull_request, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r api/requirements.txt
    - name: Run tests and collect coverage
      run: pytest --cov --cov-report xml api/
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
